[package]
name = "cprover-api-rust"
version = "0.1.0"
edition = "2021"
description = "Rust API for CBMC and assorted CProver tools"
repository = "https://github.com/diffblue/cbmc"
documentation = "https://diffblue.github.io/cbmc/"
license = "BSD-4-Clause"
exclude = ["other/", "module_dependencies.txt"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]
