name: Publish CBMC documentation
on: [push, pull_request]

jobs:
  # This job takes approximately 3 minutes
  publish:
    # Note that the versions used for this `publish` job should be kept in sync
    # with the `check-doxygen` job.
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doxygen
        run: |
          sudo apt update
          sudo apt-get install --no-install-recommends -y doxygen graphviz pandoc npm python3-git python3-pandocfilters

      - name: Install mermaid diagram filter
        run: |
          git clone https://github.com/raghur/mermaid-filter/
          cd mermaid-filter
          npm install --loglevel verbose
          sudo npm link --loglevel verbose
          cd ..

      - name: Build documentation
        run: |
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
          cd doc/doxygen-root && make && touch html/.nojekyll

      - name: Publish documentation
        if: ${{ github.event_name == 'push' && startsWith('refs/heads/develop', github.ref) }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: doc/doxygen-root/html
